Update visualization.py
PracticalDL/Practical-Deep-Learning-Book pull request #146
Opened 2021-01-11 10:31 UTC by MatthewTafazoli

Hello,

My name is Matthew Tafazoli, and I was emailing Ms. Siddha about changes to the visualization.py code to make it run after receiving errors when initially running the code. I was told to issue a pull request with my changes.

After receiving errors running the original code locally (I kept receiving error with the original gradcam().explain() line), I edited the code and combined it with the official gradcam documentation from the Keras website. This runs without error for me on windows.

Best Regards,

Matthew

2021-01-11 19:03 UTC, sidgan requested changes
Can you add comments in the script as well as in the README to help close gaps between the  readers coming from the book vs the name of the functions in your updates eg `make_gradcam_heatmap`

2021-01-12 03:54 UTC, sidgan approved these changes

2021-01-12 03:54 UTC, sidgan approved these changes

2021-01-12 07:28 UTC, MatthewTafazoli commented
Hello,

I updated the script to include comments explaining all the variables and inputs for each function, as well as their purpose. I'm not sure if it was necessary, but for the sake of consistency, I included comments for functions that were already in the visualization.py script that weren't changed much (ex. process_video) . I apologize for taking so long, and also I apologize if the formatting is possibly strange or if my commits were not done well, as I do not have much prior experience with Git and Pull Requests.

Best Regards,

Matthew

2021-01-13 04:32 UTC, sidgan approved these changes

2021-01-13 04:32 UTC, merged